title: helloworld
description: just another repository
template:
  repo: helloworld-template
  name: helloworld
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
  - type: createLabel
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
